// Writes src/version.ts from package.json so `bask --version` matches the release.
import { readFileSync, writeFileSync } from "node:fs";
const { version } = JSON.parse(readFileSync(new URL("../package.json", import.meta.url), "utf8"));
const out = `// Generated by scripts/gen-version.mjs from package.json. Do not edit.\nexport const VERSION = "${version}";\n`;
const target = new URL("../src/version.ts", import.meta.url);
let current = "";
try {
  current = readFileSync(target, "utf8");
} catch {}
if (current !== out) writeFileSync(target, out);
